/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "auth": {
        "wrongPassword": string;
        "wrongOldPassword": string;
        "wrongPhoneNumber": string;
        "expiredToken": string;
        "invalidToken": string;
    };
    "common": {
        "hello": string;
        "notFound": string;
        "alreadyExists": string;
        "invalid": string;
        "cannotDelete": string;
    };
    "exception": {
        "internalServerError": string;
        "notFound": string;
        "badRequest": string;
        "unauthorized": string;
        "forbidden": string;
        "methodNotAllowed": string;
    };
    "repository": {
        "admin": string;
        "customer": string;
        "user": string;
        "groupPolicy": string;
        "groupToPolicy": string;
        "policy": string;
        "userToGroupPolicy": string;
        "systemConfig": string;
        "customField": string;
        "file": string;
        "news": string;
        "newDetail": string;
        "newsToFile": string;
        "newsToSubject": string;
        "subject": string;
        "subjectDetail": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
